---@class UserIcons
---@field kind table<string, string>
---@field type table<string, string>
---@field documents table<string, string>
---@field git table<string, string>
---@field ui table<string, string>
---@field diagnostics table<string, string>
---@field misc table<string, string>

---@type UserIcons
local M = {
  kind = {
    Text = "󰦨 ",
    Method = " ",
    Function = " ",
    Constructor = " ",
    Field = " ",
    Variable = " ",
    Class = " ",
    Interface = " ",
    Module = " ",
    Property = " ",
    Unit = " ",
    Value = "󰾡 ",
    Enum = " ",
    Keyword = " ",
    Snippet = " ",
    Color = " ",
    File = " ",
    Reference = " ",
    Folder = " ",
    EnumMember = " ",
    Constant = " ",
    Struct = " ",
    Event = " ",
    Operator = " ",
    TypeParameter = " ",
    Specifier = " ",
    Statement = "",
    Recovery = " ",
    TranslationUnit = " ",
    PackExpansion = " ",
  },
  type = {
    Array = " ",
    Number = " ",
    String = " ",
    Boolean = " ",
    Object = " ",
    Template = " ",
  },
  documents = {
    File = "",
    Files = "",
    Folder = "",
    OpenFolder = "",
    EmptyFolder = "",
    EmptyOpenFolder = "",
    Unknown = "",
    Symlink = "",
    FolderSymlink = "",
  },
  git = {
    Add = " ",
    Mod = " ",
    Remove = " ",
    Untrack = " ",
    Rename = " ",
    Diff = " ",
    Repo = " ",
    Branch = " ",
    Unmerged = " ",
  },
  ui = {
    Lock = "",
    TinyCircle = "",
    Circle = "",
    BigCircle = "",
    BigUnfilledCircle = "",
    CircleWithGap = "",
    LogPoint = "",
    Close = "",
    NewFile = "",
    Search = "",
    Lightbulb = "",
    Project = "",
    Dashboard = "",
    History = "",
    Comment = "",
    Bug = "",
    Code = "",
    Telescope = " ",
    Gear = "",
    Package = "",
    List = "",
    SignIn = "",
    Check = "",
    Fire = " ",
    Note = "",
    BookMark = "",
    Pencil = " ",
    -- ChevronRight = "",
    ChevronRight = ">",
    Table = "",
    Calendar = "",
    Line = "▊",
    Evil = "",
    Debug = "",
    Run = "",
    VirtualPrefix = "",
    Next = "",
    Previous = "",
  },
  diagnostics = {
    Error = " ",
    Warning = " ",
    Information = " ",
    Question = " ",
    Hint = " ",
  },
  misc = {
    Robot = "󰚩 ",
    Squirrel = "  ",
    Tag = " ",
  },
}

return M
