local parsers = {
  "ada",
  "agda",
  "angular",
  "apex",
  "arduino",
  "asm",
  "astro",
  "authzed",
  "awk",
  "bash",
  "bass",
  "beancount",
  "bibtex",
  "bicep",
  "bitbake",
  "blade",
  "bp",
  "bpftrace",
  "brightscript",
  "c",
  "c3",
  "c_sharp",
  "caddy",
  "cairo",
  "capnp",
  "chatito",
  "circom",
  "clojure",
  "cmake",
  "comment",
  "commonlisp",
  "cooklang",
  "corn",
  "cpon",
  "cpp",
  "css",
  "csv",
  "cuda",
  "cue",
  "cylc",
  "d",
  "dart",
  "desktop",
  "devicetree",
  "dhall",
  "diff",
  "disassembly",
  "djot",
  "dockerfile",
  "dot",
  "doxygen",
  "dtd",
  "earthfile",
  "ebnf",
  "editorconfig",
  "eds",
  "eex",
  "elixir",
  "elm",
  "elsa",
  "elvish",
  "embedded_template",
  "enforce",
  "erlang",
  "facility",
  "faust",
  "fennel",
  "fidl",
  "firrtl",
  "fish",
  "foam",
  "forth",
  "fortran",
  "fsh",
  "fsharp",
  "func",
  "gap",
  "gaptst",
  "gdscript",
  "gdshader",
  "git_config",
  "git_rebase",
  "gitattributes",
  "gitcommit",
  "gitignore",
  "gleam",
  "glimmer",
  "glimmer_javascript",
  "glimmer_typescript",
  "glsl",
  "gn",
  "gnuplot",
  "go",
  "goctl",
  "godot_resource",
  "gomod",
  "gosum",
  "gotmpl",
  "gowork",
  "gpg",
  "graphql",
  "gren",
  "groovy",
  "groq",
  "gstlaunch",
  "hack",
  "hare",
  "haskell",
  "haskell_persistent",
  "hcl",
  "heex",
  "helm",
  "hjson",
  "hlsl",
  "hlsplaylist",
  "hocon",
  "hoon",
  "html",
  "htmldjango",
  "http",
  "hurl",
  "hyprlang",
  "idl",
  "idris",
  "ini",
  "inko",
  "ispc",
  "janet_simple",
  "java",
  "javadoc",
  "javascript",
  "jinja",
  "jinja_inline",
  "jjdescription",
  "jq",
  "jsdoc",
  "json",
  "json5",
  "jsonnet",
  "julia",
  "just",
  "kcl",
  "kconfig",
  "kdl",
  "kitty",
  "kos",
  "kotlin",
  "koto",
  "kusto",
  "lalrpop",
  "latex",
  "ledger",
  "leo",
  "linkerscript",
  "liquid",
  "liquidsoap",
  "llvm",
  "lua",
  "luadoc",
  "luap",
  "luau",
  "m68k",
  "make",
  "markdown",
  "markdown_inline",
  "matlab",
  "menhir",
  "mermaid",
  "meson",
  "mlir",
  "muttrc",
  "nasm",
  "nginx",
  "nickel",
  "nim",
  "nim_format_string",
  "ninja",
  "nix",
  "nqc",
  "nu",
  "objc",
  "objdump",
  "ocaml",
  "ocaml_interface",
  "ocamllex",
  "odin",
  "pascal",
  "passwd",
  "pem",
  "perl",
  "php",
  "php_only",
  "phpdoc",
  "pioasm",
  "pkl",
  "po",
  "pod",
  "poe_filter",
  "pony",
  "powershell",
  "printf",
  "prisma",
  "problog",
  "prolog",
  "promql",
  "properties",
  "proto",
  "prql",
  "psv",
  "pug",
  "puppet",
  "purescript",
  "pymanifest",
  "python",
  "ql",
  "qmldir",
  "qmljs",
  "query",
  "r",
  "racket",
  "ralph",
  "rasi",
  "razor",
  "rbs",
  "re2c",
  "readline",
  "regex",
  "rego",
  "requirements",
  "rescript",
  "rifleconf",
  "rnoweb",
  "robot",
  "robots_txt",
  "roc",
  "ron",
  "rst",
  "ruby",
  "runescript",
  "rust",
  "scala",
  "scfg",
  "scheme",
  "scss",
  "sflog",
  "slang",
  "slim",
  "slint",
  "smali",
  "smithy",
  "snakemake",
  "snl",
  "solidity",
  "soql",
  "sosl",
  "sourcepawn",
  "sparql",
  "sproto",
  "sql",
  "squirrel",
  "ssh_config",
  "starlark",
  "strace",
  "styled",
  "supercollider",
  "superhtml",
  "surface",
  "svelte",
  "sway",
  "swift",
  "sxhkdrc",
  "systemtap",
  "systemverilog",
  "t32",
  "tablegen",
  "tact",
  "tcl",
  "teal",
  "templ",
  "tera",
  "terraform",
  "textproto",
  "thrift",
  "tiger",
  "tlaplus",
  "tmux",
  "todotxt",
  "toml",
  "tsv",
  "tsx",
  "turtle",
  "twig",
  "typescript",
  "typespec",
  "typoscript",
  "typst",
  "udev",
  "ungrammar",
  "unison",
  "usd",
  "uxntal",
  "v",
  "vala",
  "vento",
  "vhdl",
  "vhs",
  "vim",
  "vimdoc",
  "vrl",
  "vue",
  "wgsl",
  "wgsl_bevy",
  "wing",
  "wit",
  "wxml",
  "xcompose",
  "xml",
  "xresources",
  "yaml",
  "yang",
  "yuck",
  "zathurarc",
  "zig",
  "ziggy",
  "ziggy_schema",
  "zsh",
}

local highlight_disable = { css = true, csv = true }
local indent_disable = { python = true, css = true }

local M = {
  "nvim-treesitter/nvim-treesitter",
  dependencies = {
    "OXY2DEV/markview.nvim",
  },
  build = ":TSUpdate",
  branch = "main",
  lazy = false,
}

M.config = function()
  -- Migrated from master branch (require("nvim-treesitter.configs").setup) to main branch API.
  -- The main branch dropped the module system entirely. Features previously configured as
  -- modules inside setup {} now must be handled separately:
  --
  -- STILL WORKING (handled below or by their own plugins):
  --   - highlight   → vim.treesitter.start() via FileType autocmd
  --   - indent      → indentexpr via FileType autocmd
  --   - endwise     → nvim-treesitter-endwise works standalone (no config needed)
  --   - matchup     → vim-matchup works standalone (no treesitter module needed)
  --   - autopairs   → handled by the autopairs plugin itself
  --
  -- TEMPORARILY LOST (plugins not yet updated for main branch):
  --   - textsubjects → see nvim-treesitter-textsubjects.lua
  --
  -- PERMANENTLY LOST (plugin archived, replacement not ready):
  --   - refactor     → see nvim-treesitter-refactor.lua
  --
  -- REMOVED (no longer exists in main branch, no equivalent):
  --   - auto_install → removed; use :TSInstall or require("nvim-treesitter").install() instead

  require("nvim-treesitter").setup {}

  -- Install parsers (replaces ensure_installed, async and no-op if already installed)
  require("nvim-treesitter").install(parsers)

  -- Enable treesitter highlighting and indentation via FileType autocmd
  vim.api.nvim_create_autocmd("FileType", {
    group = vim.api.nvim_create_augroup("NvimTreesitterSetup", { clear = true }),
    callback = function(args)
      local ft = args.match
      if not highlight_disable[ft] then
        pcall(vim.treesitter.start, args.buf)
      end
      if not indent_disable[ft] then
        vim.bo[args.buf].indentexpr = "v:lua.require'nvim-treesitter'.indentexpr()"
      end
    end,
  })
end

return M
