local M = {
  "nvim-treesitter/nvim-treesitter",
  dependencies = {
    "OXY2DEV/markview.nvim",
  },
  build = ":TSUpdate",
  event = "VeryLazy",
}

M.config = function()
  require("nvim-treesitter.configs").setup {
    ensure_installed = {
      "ada",
      "agda",
      "angular",
      "apex",
      "arduino",
      "asm",
      "astro",
      "authzed",
      "awk",
      "bash",
      "bass",
      "beancount",
      "bibtex",
      "bicep",
      "bitbake",
      "blade",
      "blueprint",
      "bp",
      "brightscript",
      "c",
      "c_sharp",
      "caddy",
      "cairo",
      "capnp",
      "chatito",
      "circom",
      "clojure",
      "cmake",
      "comment",
      "commonlisp",
      "cooklang",
      "corn",
      "cpon",
      "cpp",
      "css",
      "csv",
      "cuda",
      "cue",
      "cylc",
      "d",
      "dart",
      "desktop",
      "devicetree",
      "dhall",
      "diff",
      "disassembly",
      "djot",
      "dockerfile",
      "dot",
      "doxygen",
      "dtd",
      "earthfile",
      "ebnf",
      "editorconfig",
      "eds",
      "eex",
      "elixir",
      "elm",
      "elsa",
      "elvish",
      "embedded_template",
      "enforce",
      "erlang",
      "facility",
      "faust",
      "fennel",
      "fidl",
      "firrtl",
      "fish",
      "foam",
      "forth",
      "fortran",
      "fsh",
      "fsharp",
      "func",
      "fusion",
      "gap",
      "gaptst",
      "gdscript",
      "gdshader",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "gleam",
      "glimmer",
      "glimmer_javascript",
      "glimmer_typescript",
      "glsl",
      "gn",
      "gnuplot",
      "go",
      "goctl",
      "godot_resource",
      "gomod",
      "gosum",
      "gotmpl",
      "gowork",
      "gpg",
      "graphql",
      "gren",
      "groovy",
      "gstlaunch",
      "hack",
      "hare",
      "haskell",
      "haskell_persistent",
      "hcl",
      "heex",
      "helm",
      "hjson",
      "hlsl",
      "hlsplaylist",
      "hocon",
      "hoon",
      "html",
      "htmldjango",
      "http",
      "hurl",
      "hyprlang",
      "idl",
      "idris",
      "ini",
      "inko",
      -- "ipkg", -- NOTE: Alreay removed with upstream
      "ispc",
      "janet_simple",
      "java",
      "javadoc",
      "javascript",
      "jinja",
      "jinja_inline",
      "jq",
      "jsdoc",
      "json",
      "json5",
      "jsonc",
      "jsonnet",
      "julia",
      "just",
      "kcl",
      "kconfig",
      "kdl",
      "kotlin",
      "koto",
      "kusto",
      "lalrpop",
      "latex",
      "ledger",
      "leo",
      "linkerscript",
      "liquid",
      "liquidsoap",
      "llvm",
      "lua",
      "luadoc",
      "luap",
      "luau",
      "m68k",
      "make",
      "markdown",
      "markdown_inline",
      "matlab",
      "menhir",
      "mermaid",
      "meson",
      "mlir",
      "muttrc",
      "nasm",
      "nginx",
      "nickel",
      "nim",
      "nim_format_string",
      "ninja",
      "nix",
      "norg",
      "nqc",
      "nu",
      "objc",
      "objdump",
      "ocaml",
      "ocaml_interface",
      "ocamllex",
      "odin",
      "pascal",
      "passwd",
      "pem",
      "perl",
      "php",
      "php_only",
      "phpdoc",
      "pioasm",
      "po",
      "pod",
      "poe_filter",
      "pony",
      "powershell",
      "printf",
      "prisma",
      "problog",
      "prolog",
      "promql",
      "properties",
      "proto",
      "prql",
      "psv",
      "pug",
      "puppet",
      "purescript",
      "pymanifest",
      "python",
      "ql",
      "qmldir",
      "qmljs",
      "query",
      "r",
      "racket",
      "ralph",
      "rasi",
      "razor",
      "rbs",
      "re2c",
      "readline",
      "regex",
      "rego",
      "requirements",
      "rescript",
      "rnoweb",
      "robot",
      "robots",
      "roc",
      "ron",
      "rst",
      "ruby",
      "runescript",
      "rust",
      "scala",
      "scfg",
      "scheme",
      "scss",
      "sflog",
      "slang",
      "slim",
      "slint",
      "smali",
      "smithy",
      "snakemake",
      "solidity",
      "soql",
      "sosl",
      "sourcepawn",
      "sparql",
      "sql",
      "squirrel",
      "ssh_config",
      "starlark",
      "strace",
      "styled",
      "supercollider",
      "superhtml",
      "surface",
      "svelte",
      "sway",
      "swift",
      "sxhkdrc",
      "systemtap",
      "t32",
      "tablegen",
      "tact",
      "tcl",
      "teal",
      "templ",
      "tera",
      "terraform",
      "textproto",
      "thrift",
      "tiger",
      "tlaplus",
      "tmux",
      "todotxt",
      "toml",
      "tsv",
      "tsx",
      "turtle",
      "twig",
      "typescript",
      "typespec",
      "typoscript",
      "typst",
      "udev",
      "ungrammar",
      "unison",
      "usd",
      "uxntal",
      "v",
      "vala",
      "vento",
      "verilog",
      "vhdl",
      "vhs",
      "vim",
      "vimdoc",
      "vrl",
      "vue",
      "wgsl",
      "wgsl_bevy",
      "wing",
      "wit",
      "xcompose",
      "xml",
      "xresources",
      "yaml",
      "yang",
      "yuck",
      "zathurarc",
      "zig",
      "ziggy",
      "ziggy_schema",
    },
    highlight = {
      enable = true,
      disable = {
        "css",
        "csv", -- NOTE: To make rainbow_csv work
      },
    },
    auto_install = true,
    autopairs = {
      enable = true,
    },
    indent = {
      enable = true,
      disable = {
        "python",
        "css",
      },
    },
    textsubjects = {
      enable = true,
      prev_selection = ",",
      keymaps = {
        ["."] = "textsubjects-smart",
        [";"] = "textsubjects-container-outer",
        ["i;"] = "textsubjects-container-inner",
      },
    },
    refactor = {
      highlight_definitions = {
        enable = true,
        clear_on_cursor_move = true,
      },
      highlight_current_scope = {
        enable = false,
      },
      smart_rename = {
        enable = true,
        keymaps = {
          smart_rename = "grr",
        },
      },
      navigation = {
        enable = true,
        keymaps = {
          goto_definition = "gnd",
          list_definitions = "gnD",
          list_definitions_toc = "gO",
          goto_next_usage = "<a-*>",
          goto_previous_usage = "<a-#>",
        },
      },
    },
    matchup = {
      enable = true,
      disable = {},
      disable_virtual_text = false,
      include_match_words = true,
    },
    endwise = {
      enable = true,
    },
  }
end

return M
